# Used for configuring local dependencies only
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: chatdoc_db
    restart: on-failure
    environment:
      - POSTGRES_DB=chatdoc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - chatdoc_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  chatdoc_db: